"""create work management tables

Revision ID: 4ed9e24ae78d
Revises: 
Create Date: 2026-05-02 00:20:13.877660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ed9e24ae78d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_created_by'), 'users', ['created_by'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_is_deleted'), 'users', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_users_updated_at'), 'users', ['updated_at'], unique=False)
    op.create_index(op.f('ix_users_updated_by'), 'users', ['updated_by'], unique=False)
    op.create_table('projects',
    sa.Column('project_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'CLOSE', name='project_status'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('managed_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['managed_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('project_id')
    )
    op.create_index(op.f('ix_projects_created_at'), 'projects', ['created_at'], unique=False)
    op.create_index(op.f('ix_projects_created_by'), 'projects', ['created_by'], unique=False)
    op.create_index(op.f('ix_projects_is_deleted'), 'projects', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_projects_managed_by'), 'projects', ['managed_by'], unique=False)
    op.create_index(op.f('ix_projects_status'), 'projects', ['status'], unique=False)
    op.create_index(op.f('ix_projects_title'), 'projects', ['title'], unique=False)
    op.create_index(op.f('ix_projects_updated_at'), 'projects', ['updated_at'], unique=False)
    op.create_index(op.f('ix_projects_updated_by'), 'projects', ['updated_by'], unique=False)
    op.create_table('work_items',
    sa.Column('work_item_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('display_id', sa.Integer(), nullable=False),
    sa.Column('item_type', sa.Enum('STORY', 'TASK', name='work_item_type'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('TODO', 'IN_PROGRESS', 'CODE_COMPLETE', 'DEPLOYED_ON_STAGE', 'DONE', name='work_item_status'), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('assigned_by', sa.UUID(), nullable=False),
    sa.Column('assigned_to', sa.UUID(), nullable=False),
    sa.Column('linked_work_item_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['linked_work_item_id'], ['work_items.work_item_id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ),
    sa.PrimaryKeyConstraint('work_item_id'),
    sa.UniqueConstraint('project_id', 'display_id', name='uq_work_items_project_display')
    )
    op.create_index(op.f('ix_work_items_assigned_by'), 'work_items', ['assigned_by'], unique=False)
    op.create_index(op.f('ix_work_items_assigned_to'), 'work_items', ['assigned_to'], unique=False)
    op.create_index(op.f('ix_work_items_created_at'), 'work_items', ['created_at'], unique=False)
    op.create_index(op.f('ix_work_items_created_by'), 'work_items', ['created_by'], unique=False)
    op.create_index(op.f('ix_work_items_end_date'), 'work_items', ['end_date'], unique=False)
    op.create_index(op.f('ix_work_items_is_deleted'), 'work_items', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_work_items_item_type'), 'work_items', ['item_type'], unique=False)
    op.create_index(op.f('ix_work_items_linked_work_item_id'), 'work_items', ['linked_work_item_id'], unique=False)
    op.create_index('ix_work_items_project_display', 'work_items', ['project_id', 'display_id'], unique=False)
    op.create_index(op.f('ix_work_items_project_id'), 'work_items', ['project_id'], unique=False)
    op.create_index(op.f('ix_work_items_start_date'), 'work_items', ['start_date'], unique=False)
    op.create_index(op.f('ix_work_items_status'), 'work_items', ['status'], unique=False)
    op.create_index(op.f('ix_work_items_title'), 'work_items', ['title'], unique=False)
    op.create_index(op.f('ix_work_items_updated_at'), 'work_items', ['updated_at'], unique=False)
    op.create_index(op.f('ix_work_items_updated_by'), 'work_items', ['updated_by'], unique=False)
    op.create_table('comments',
    sa.Column('comment_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('work_item_id', sa.UUID(), nullable=False),
    sa.Column('comment_reply_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['comment_reply_id'], ['comments.comment_id'], ),
    sa.ForeignKeyConstraint(['work_item_id'], ['work_items.work_item_id'], ),
    sa.PrimaryKeyConstraint('comment_id')
    )
    op.create_index(op.f('ix_comments_comment_reply_id'), 'comments', ['comment_reply_id'], unique=False)
    op.create_index(op.f('ix_comments_created_at'), 'comments', ['created_at'], unique=False)
    op.create_index(op.f('ix_comments_created_by'), 'comments', ['created_by'], unique=False)
    op.create_index(op.f('ix_comments_is_deleted'), 'comments', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_comments_updated_at'), 'comments', ['updated_at'], unique=False)
    op.create_index(op.f('ix_comments_updated_by'), 'comments', ['updated_by'], unique=False)
    op.create_index(op.f('ix_comments_work_item_id'), 'comments', ['work_item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_comments_work_item_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_updated_by'), table_name='comments')
    op.drop_index(op.f('ix_comments_updated_at'), table_name='comments')
    op.drop_index(op.f('ix_comments_is_deleted'), table_name='comments')
    op.drop_index(op.f('ix_comments_created_by'), table_name='comments')
    op.drop_index(op.f('ix_comments_created_at'), table_name='comments')
    op.drop_index(op.f('ix_comments_comment_reply_id'), table_name='comments')
    op.drop_table('comments')
    op.drop_index(op.f('ix_work_items_updated_by'), table_name='work_items')
    op.drop_index(op.f('ix_work_items_updated_at'), table_name='work_items')
    op.drop_index(op.f('ix_work_items_title'), table_name='work_items')
    op.drop_index(op.f('ix_work_items_status'), table_name='work_items')
    op.drop_index(op.f('ix_work_items_start_date'), table_name='work_items')
    op.drop_index(op.f('ix_work_items_project_id'), table_name='work_items')
    op.drop_index('ix_work_items_project_display', table_name='work_items')
    op.drop_index(op.f('ix_work_items_linked_work_item_id'), table_name='work_items')
    op.drop_index(op.f('ix_work_items_item_type'), table_name='work_items')
    op.drop_index(op.f('ix_work_items_is_deleted'), table_name='work_items')
    op.drop_index(op.f('ix_work_items_end_date'), table_name='work_items')
    op.drop_index(op.f('ix_work_items_created_by'), table_name='work_items')
    op.drop_index(op.f('ix_work_items_created_at'), table_name='work_items')
    op.drop_index(op.f('ix_work_items_assigned_to'), table_name='work_items')
    op.drop_index(op.f('ix_work_items_assigned_by'), table_name='work_items')
    op.drop_table('work_items')
    op.drop_index(op.f('ix_projects_updated_by'), table_name='projects')
    op.drop_index(op.f('ix_projects_updated_at'), table_name='projects')
    op.drop_index(op.f('ix_projects_title'), table_name='projects')
    op.drop_index(op.f('ix_projects_status'), table_name='projects')
    op.drop_index(op.f('ix_projects_managed_by'), table_name='projects')
    op.drop_index(op.f('ix_projects_is_deleted'), table_name='projects')
    op.drop_index(op.f('ix_projects_created_by'), table_name='projects')
    op.drop_index(op.f('ix_projects_created_at'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_users_updated_by'), table_name='users')
    op.drop_index(op.f('ix_users_updated_at'), table_name='users')
    op.drop_index(op.f('ix_users_is_deleted'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_created_by'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
